MONIT-31546: update logs to not replace 'tag' with '_tag'
wavefrontHQ/java-lib pull request #134
Opened 2022-11-21 18:32 UTC by xuranchen

2022-11-21 19:14 UTC, deosu approved these changes
Paired with @xuranchen to review the PR. The changes look good.

2022-11-23 17:48 UTC, laullon requested changes

2022-11-23 17:48 UTC, laullon commented on java-lib/src/main/java/com/wavefront/ingester/AbstractIngesterFormatter.java
>    public static String getHost(@Nullable List<Annotation> annotations,
lets rename it to `getHostAndNormalizeTabs`
and add ad `//TODO: review why we change tag to _tag here`

2022-11-23 17:56 UTC, laullon approved these changes

2022-11-23 17:56 UTC, merged